class Constants:
    TRAIN = 'train'
    DATA = 'data'
    IMAGE_PATH = 'image_path'
    OUTPUT_DIR = 'output_dir'
    LR = 'lr'
    OPTIMIZER = 'optimizer'
    BATCH_SIZE = 'batch_size'
    MLP_HIDDEN_LAYERS = 'mlp_hidden_layers'
    MLP_NEURONS_PER_LAYER = 'mlp_neurons_per_layer'
    HASH_SIZE = 'hash_size'
    ADAM_B1 = 'adam_b1'
    ADAM_B2 = 'adam_b2'
    EPOCHS = 'epochs'
